### ISSUE TITLE
Unstable 

### ISSUE THREAD

**Issue by youhusky** [LearnerChao/LinkDriver#1]
/Library/Ruby/Gems/2.0.0/gems/watir-webdriver-0.9.1/lib/watir-webdriver/elements/element.rb:536:in `assert_element_found': unable to locate element, using {:element=>#<Selenium::WebDriver::Element:0x1dd072697df9fba2 id="0.5434227146135548-15">} (Watir::Exception::UnknownObjectException)
    from /Library/Ruby/Gems/2.0.0/gems/watir-webdriver-0.9.1/lib/watir-webdriver/elements/element.rb:524:in`ensure_not_stale'
    from /Library/Ruby/Gems/2.0.0/gems/watir-webdriver-0.9.1/lib/watir-webdriver/elements/element.rb:503:in `assert_exists'
    from /Library/Ruby/Gems/2.0.0/gems/watir-webdriver-0.9.1/lib/watir-webdriver/elements/element.rb:561:in`ensure_context'
    from /Library/Ruby/Gems/2.0.0/gems/watir-webdriver-0.9.1/lib/watir-webdriver/elements/element.rb:545:in `locate'
    from /Library/Ruby/Gems/2.0.0/gems/watir-webdriver-0.9.1/lib/watir-webdriver/elements/element.rb:505:in`assert_exists'
    from /Library/Ruby/Gems/2.0.0/gems/watir-webdriver-0.9.1/lib/watir-webdriver/elements/element.rb:81:in `text'
    from /Users/Joshua/Documents/Code/LinkDriver/linkedin_page.rb:89:in`name_of_person'
    from step_entry_point.rb:66:in `block in <main>'
    from step_entry_point.rb:64:in`each'
    from step_entry_point.rb:64:in `each_with_index'
    from step_entry_point.rb:64:in`<main>'

**Comment by LearnerChao** [comment]
Fixed. Already pushed to master
